<?php

namespace Doi\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BatchRepository extends EntityRepository
{
	public function findFull($batchId)
	{
		return $this->_em->createQueryBuilder()
			->select('b, sbu, ba, d')
			->from('\Doi\Entity\Batch', 'b')
			->innerJoin('b.submittedBy', 'sbu')
			->innerJoin('b.batchArticles', 'ba')
			->innerJoin('ba.doi', 'd')
			->where('b.batchId = :batchId')
			->setParameter('batchId', $batchId)
			->getQuery()
			->getOneOrNullResult();
	}

	public function findByDoi($doi)
	{
		return $this->_em->createQueryBuilder()
			->select('b, sbu, ba, d')
			->from('\Doi\Entity\Batch', 'b')
			->innerJoin('b.submittedBy', 'sbu')
			->innerJoin('b.batchArticles', 'ba')
			->innerJoin('ba.doi', 'd')
			->where('d.doi = :doi')
			->setParameter('doi', $doi)
			->getQuery()
			->getResult();
	}
}
