<?php

namespace Doi\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BatchArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BatchArticleRepository extends EntityRepository
{
	public function findByBatchIdAndDoi($batchId, $doi)
	{
		return $this->_em->createQueryBuilder()
			->select('ba')
			->from('\Doi\Entity\BatchArticle', 'ba')
			->innerJoin('b.batch', 'b')
			->innerJoin('b.doi', 'd')
			->where('d.doi = :doi AND b.batchId = :batchId')
			->setParameter('batchId', $batchId)
			->setParameter('doi', $doi)
			->getQuery()
			->getOneOrNullResult();
	}
}
