<?php

namespace Doi\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoiRepository extends EntityRepository
{

	public function findByDoi($doi)
	{
		return $this->_em->createQueryBuilder()
			->select('d, dr, u')
			->from('\Doi\Entity\Doi', 'd')
			->innerJoin('d.doiRequest', 'dr')
			->leftJoin('d.user', 'u')
			->where('d.doi = :doi')
			->setParameter('doi', $doi)
			->getQuery()
			->getOneOrNullResult();
	}

}
